title: PowerShell
author: Raymond Dibeler
email: raymond.w.dibeler@outlook.com


# social links
github_username:  https://github.com/RWDIV

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
